name: Create Issue Branch

on:
  issues:
    types: [opened]

jobs:
  create_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
